name: rebuilding
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v3
     - name: formatter_lib
       shell: bash
       run: |
          cd formatter_lib/
          cmake -H. -B_build
          cmake --build _build
     - name: formatter_ex_lib
       shell: bash
       run: |
          cd formatter_ex_lib/
          cmake -H. -B_build
          cmake --build _build
     - name: Test
       shell: bash
       run: |
           cd hello_world_application/
           cmake CMakeLists.txt
           make
           ./Test

     - name: reshatel.cpp
       shell: bash
       run: |
           cd solver_application/
           cmake CMakeLists.txt
           ./reshatel
       
